#!/bin/bash

error_message() {
    if [ ! $? -eq 0 ]; then
        echo "Sorry, $packages does not exist!"
        exit 1
    fi
}

echo "Which packages are you looking for?"
read packages

command -v $packages >/dev/null

if [ $? -eq 0 ]; then
    echo "$packages is already installed!"
else
    while true; do
        sudo -l
        if [ $? -eq 0 ]; then
            break
        fi
    done

    echo "Looking for $packages..."
    sleep 1

    package_manager=""

    if [ -f /etc/apt/sources.list ]; then
        package_manager="apt"
    elif [ -f /etc/yum.conf ]; then
        package_manager="yum"
    elif [ -f /etc/dnf/dnf.conf ]; then
        package_manager="dnf"
    elif [ -f /etc/zypp/zypp.conf ]; then
        package_manager="zypper"
    elif [ -f /etc/pacman.conf ]; then
        package_manager="pacman"
    elif [ -d /usr/portage ]; then
        package_manager="portage"
    elif [ -d /nix ]; then
        package_manager="nix"
    else
        echo "No supported package manager found on this system."
        exit 1
    fi

    echo "Using package manager: $package_manager"

    case $package_manager in
        "apt")
            sudo apt update && sudo apt install -y $packages
            error_message
            ;;
        "yum")
            sudo yum install -y $packages
            error_message
            ;;
        "dnf")
            sudo dnf install -y $packages
            error_message
            ;;
        "zypper")
            sudo zypper install -y $packages
            error_message
            ;;
        "pacman")
            sudo pacman -Syu --noconfirm && sudo pacman -S --noconfirm $packages
            error_message
            ;;
        "portage")
            sudo emerge $packages
            error_message
            ;;
        "nix")
            sudo nix-env -iA nixpkgs.$packages
            error_message
            ;;
        *)
            echo "Unsupported package manager: $package_manager"
            exit 1
            ;;
    esac

    echo "$packages is now installed!"
fi
